### PR TITLE
patcher

### PR DESCRIPTION
**Pull request by moddedmcplayer**

### CODE REVIEW

**Comment by moddedmcplayer** [comment]
- [ ] needs testing
- [ ] needs to be called from launcher

**Comment by moddedmcplayer** [comment]
gay git

**Comment by TheUltiOne** [comment]
no you're gay

**Comment by moddedmcplayer** [comment]
maybe

**Comment by moddedmcplayer** [comment]
FUCK MISSCLICK

**Comment by moddedmcplayer** [comment]
dead

**Pull request closed without merging**
